// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIsdQEbSqDOmhetzvpd55aCc0vvHqK2-0',
    appId: '1:739625964121:web:4cdf1cea39691bacf2d748',
    messagingSenderId: '739625964121',
    projectId: 'phone-auth-using-bloc-5b238',
    authDomain: 'phone-auth-using-bloc-5b238.firebaseapp.com',
    storageBucket: 'phone-auth-using-bloc-5b238.appspot.com',
    measurementId: 'G-0T31VPVSDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD86Yv4NDVNwqtWB3Mqumxwd12GlnLfpo',
    appId: '1:739625964121:android:494e4512e869cbe4f2d748',
    messagingSenderId: '739625964121',
    projectId: 'phone-auth-using-bloc-5b238',
    storageBucket: 'phone-auth-using-bloc-5b238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7HEJesdIYMZPqnZdzyxmVVe4en3lZ7C0',
    appId: '1:739625964121:ios:370d8b422189030bf2d748',
    messagingSenderId: '739625964121',
    projectId: 'phone-auth-using-bloc-5b238',
    storageBucket: 'phone-auth-using-bloc-5b238.appspot.com',
    androidClientId: '739625964121-liutd34mmg68ucug74nmoqmccfbi5e3f.apps.googleusercontent.com',
    iosClientId: '739625964121-l8crquv0mbqdclhvi4d621r9b1kh4v2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneauthUsingBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7HEJesdIYMZPqnZdzyxmVVe4en3lZ7C0',
    appId: '1:739625964121:ios:ddd01093ee23e845f2d748',
    messagingSenderId: '739625964121',
    projectId: 'phone-auth-using-bloc-5b238',
    storageBucket: 'phone-auth-using-bloc-5b238.appspot.com',
    androidClientId: '739625964121-liutd34mmg68ucug74nmoqmccfbi5e3f.apps.googleusercontent.com',
    iosClientId: '739625964121-4gg6cin78ord7l8f2dcfnf01adkusaoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneauthUsingBloc.RunnerTests',
  );
}
